### PR TITLE
Fix build setup and pivot to GitHub Actions

### PR DESCRIPTION
**Pull request by leoarnold**
This fixes unit tests which failes because they tried to use
an image files from another gem and did not find it in the
expected location. We simply add the file as a fixture
to the project at hand.

Also, this project was still using Travis CI **dot org**
which was deprecated in favor of **dot com**, and then again
Travis CI introduced restrictions to protect their
infrastructure which are just detremental to OSS development:

https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

Hence we move all tests over to GitHub Actions.

### CODE REVIEW

**Comment by petergoldstein** [comment]
@pointlessone I would prioritize merging this.

**Comment by pointlessone** [comment]
@petergoldstein Can we have a copy of the prawnpdf/prawn setup here? Maybe apart from RuboCop part. I don't believe this repos even has RuboCop set up in it.

**Comment by petergoldstein** [comment]
@pointlessone Sure.  I'll set up Rubocop as well with the same config and just add a .rubocop_todo.yml for all existing lints.

One quick question - can I change the `pull_request_target` to `pull_request`, as that's the more standard configuration?

I'll put up a PR with that in the next 24 hours.

**Comment by pointlessone** [comment]
@petergoldstein Yes, we probably should change that on other repos to.

I suggest splitting RuboCop into a separate PR or even skipping it altogether. I imagine it will take some effort to fix all the issues there and it's not immediately valuable.

**Comment by petergoldstein** [comment]
@pointlessone Ok.  I'll split Rubocop out separately.

Any objection to me removing the custom bundle cache logic?  There's a built in [bundle-cache in the ruby/setup-ruby action](https://github.com/ruby/setup-ruby#caching-bundle-install-automatically) that does this all automatically.  Any objection to me using that?  It works fine with multiple rubies.  That will simplify the GitHub Actions file significantly.

**Comment by pointlessone** [comment]
Please keep the custom bundle cache logic. It has been discussed extensively in prawnpdf/prawn#1190 and ruby/setup-ruby#136. It's been a while since those discussions but I don't think much has changed since.

**Pull request closed without merging**
