### PR TITLE
Drop Mocha

### PR DESCRIPTION
**Pull request by cheba**
This PR completely removes mocha from deps. In combination with #63 this should give green build on 2.0.0-p0.

### CODE REVIEW

**Comment by jessedoyle** [comment]
@cheba - Awesome work! All tests pass for my local `2.0.0-p0` interpreter.

So we should have a completely green build then once #63 is merged in?

**Comment by cheba** [comment]
@jessedoyle Yep.

**Comment by jessedoyle** [comment]
Perfect. Well I'm all for merging both ASAP then.

**Comment by packetmonkey** [comment]
Both merged, lets see how it goes!

Thanks!

**Comment by packetmonkey** [comment]
[Build 209](https://travis-ci.org/prawnpdf/prawn-table/builds/99318917) is green! Thanks again

**Pull request merged**
